S3PayloadBucket = "redspot631013143897"
S3PayloadKey = "payload"
S3OutputBucket = "redspot631013143897"
S3OutputPrefix = "outputs/"
ImageTag = "631013143897.dkr.ecr.eu-west-2.amazonaws.com/redspot"
InstanceProfile = "redspot-instance-profile"
KeyPair = "redspot"